# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (weekly on Sunday at midnight)
  schedule: [{ cron: "0 0 * * 0" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}

          # Options
          user: mranv
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          config_display: large
          
          # Achievements - compact display
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, developer, infographile
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # Languages - simplified
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_indepth: no
          
          # Recent activity - lightweight
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Code habits - reduced scope
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 7
          plugin_habits_facts: no
          plugin_habits_from: 100
          
          commits_authoring: Anubhav Gain, mranv, mranv@users.noreply.github.com
